export default {
  createInviteCode: require('./createInviteCode'),
  deleteProject: require('./deleteProject'),
  findChapters: require('./findChapters'),
  findPhases: require('./findPhases'),
  findPhaseSummaries: require('./findPhaseSummaries'),
  findMembers: require('./findMembers'),
  findProjects: require('./findProjects'),
  findProjectsForCycle: require('./findProjectsForCycle'),
  findRetrospectiveSurveys: require('./findRetrospectiveSurveys'),
  getChapter: require('./getChapter'),
  getCycleVotingResults: require('./getCycleVotingResults'),
  getProject: require('./getProject'),
  getProjectSummary: require('./getProjectSummary'),
  getRetrospectiveSurvey: require('./getRetrospectiveSurvey'),
  getMemberSummary: require('./getMemberSummary'),
  importProject: require('./importProject'),
  lockSurveyForMember: require('./lockSurveyForMember'),
  reassignMembersToChapter: require('./reassignMembersToChapter'),
  saveChapter: require('./saveChapter'),
  saveRetrospectiveSurveyResponses: require('./saveRetrospectiveSurveyResponses'),
  submitSurvey: require('./submitSurvey'),
  unlockSurveyForMember: require('./unlockSurveyForMember'),
  updateMember: require('./updateMember'),
}
